name: autoblack
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.6
      - name: Install Black
        run: pip install black
      - name: Run black --check .
        run: black --line-length 120 --check .
      - name: If needed, commit black changes to the pull request
        if: failure()
        run: |
          git checkout `basename $GITHUB_REF`
          black --line-length 120 .
          git config --global user.name 'autoblack'
          git config --global user.email 'cclauss@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git commit -am "fixup: Format Python code with Black"
          git push `basename $GITHUB_REF`