name: "release-black8-flake8-sphinx"
on:
  push:
    branches:
      - main
jobs:
  black-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: black
        uses: psf/black@stable
        with:
          options: "--line-length 120"
          src: "."
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'pd-github-actions'
          git config --global user.email 'github-actions@paralleldomain.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Black formatted"
          git push
        shell: bash
  flake8-lint:
    needs: black-format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.8'
      - uses: TrueBrain/actions-flake8@v2
        with:
          max_line_length: 120
          ignore: "E203,F401,F407,W503"
  sphinx-build:
    needs: flake8-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Sphinx API Documentation
        run: |
          sudo apt-get update
          sudo apt-get install pandoc
          python -m pip install --upgrade pip
          python -m pip install -e ".[data_lab,statistics]"
          python -m pip install -r docs/requirements.txt
          sphinx-build -b html docs/source docs/build --keep-going
      - uses: actions/upload-artifact@v3
        with:
          name: API Documentation
          path: docs/build/
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
