name: "sphinx"
on:
  pull_request:
    branches:
      - main
jobs:
  sphinx-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Sphinx API Documentation
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
          python -m pip install -r docs/requirements.txt
          sphinx-build -b html docs/source docs/build --keep-going -W
      - uses: actions/upload-artifact@v1
        with:
          name: API Documentation
          path: docs/build/
      - name: Deploy to GH Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build
